In [6]:
data = [
    {
        'name': 'Instagram',
        'follower_count': 346,
        'description': 'Social media platform',
        'country': 'United States'
    },
    {
        'name': 'Cristiano Ronaldo',
        'follower_count': 215,
        'description': 'Footballer',
        'country': 'Portugal'
    },
    {
        'name': 'Ariana Grande',
        'follower_count': 183,
        'description': 'Musician and actress',
        'country': 'United States'
    },
    {
        'name': 'Dwayne Johnson',
        'follower_count': 181,
        'description': 'Actor and professional wrestler',
        'country': 'United States'
    },
    {
        'name': 'Selena Gomez',
        'follower_count': 174,
        'description': 'Musician and actress',
        'country': 'United States'
    },
    {
        'name': 'Kylie Jenner',
        'follower_count': 172,
        'description': 'Reality TV personality and businesswoman and Self-Made Billionaire',
        'country': 'United States'
    },
    {
        'name': 'Kim Kardashian',
        'follower_count': 167,
        'description': 'Reality TV personality and businesswoman',
        'country': 'United States'
    },
    {
        'name': 'Lionel Messi',
        'follower_count': 149,
        'description': 'Footballer',
        'country': 'Argentina'
    },
    {
        'name': 'Beyoncé',
        'follower_count': 145,
        'description': 'Musician',
        'country': 'United States'
    },
    {
        'name': 'Neymar',
        'follower_count': 138,
        'description': 'Footballer',
        'country': 'Brasil'
    },
    {
        'name': 'National Geographic',
        'follower_count': 135,
        'description': 'Magazine',
        'country': 'United States'
    },
    {
        'name': 'Justin Bieber',
        'follower_count': 133,
        'description': 'Musician',
        'country': 'Canada'
    },
    {
        'name': 'Taylor Swift',
        'follower_count': 131,
        'description': 'Musician',
        'country': 'United States'
    },
    {
        'name': 'Kendall Jenner',
        'follower_count': 127,
        'description': 'Reality TV personality and Model',
        'country': 'United States'
    },
    {
        'name': 'Jennifer Lopez',
        'follower_count': 119,
        'description': 'Musician and actress',
        'country': 'United States'
    },
    {
        'name': 'Nicki Minaj',
        'follower_count': 113,
        'description': 'Musician',
        'country': 'Trinidad and Tobago'
    },
    {
        'name': 'Nike',
        'follower_count': 109,
        'description': 'Sportswear multinational',
        'country': 'United States'
    },
    {
        'name': 'Khloé Kardashian',
        'follower_count': 108,
        'description': 'Reality TV personality and businesswoman',
        'country': 'United States'
    },
    {
        'name': 'Miley Cyrus',
        'follower_count': 107,
        'description': 'Musician and actress',
        'country': 'United States'
    },
    {
        'name': 'Katy Perry',
        'follower_count': 94,
        'description': 'Musician',
        'country': 'United States'
    },
    {
        'name': 'Kourtney Kardashian',
        'follower_count': 90,
        'description': 'Reality TV personality',
        'country': 'United States'
    },
    {
        'name': 'Kevin Hart',
        'follower_count': 89,
        'description': 'Comedian and actor',
        'country': 'United States'
    },
    {
        'name': 'Ellen DeGeneres',
        'follower_count': 87,
        'description': 'Comedian',
        'country': 'United States'
    },
    {
        'name': 'Real Madrid CF',
        'follower_count': 86,
        'description': 'Football club',
        'country': 'Spain'
    },
    {
        'name': 'FC Barcelona',
        'follower_count': 85,
        'description': 'Football club',
        'country': 'Spain'
    },
    {
        'name': 'Rihanna',
        'follower_count': 81,
        'description': 'Musician and businesswoman',
        'country': 'Barbados'
    },
    {
        'name': 'Demi Lovato',
        'follower_count': 80,
        'description': 'Musician and actress',
        'country': 'United States'
    },
    {
        'name': "Victoria's Secret",
        'follower_count': 69,
        'description': 'Lingerie brand',
        'country': 'United States'
    },
    {
        'name': 'Zendaya',
        'follower_count': 68,
        'description': 'Actress and musician',
        'country': 'United States'
    },
    {
        'name': 'Shakira',
        'follower_count': 66,
        'description': 'Musician',
        'country': 'Colombia'
    },
    {
        'name': 'Drake',
        'follower_count': 65,
        'description': 'Musician',
        'country': 'Canada'
    },
    {
        'name': 'Chris Brown',
        'follower_count': 64,
        'description': 'Musician',
        'country': 'United States'
    },
    {
        'name': 'LeBron James',
        'follower_count': 63,
        'description': 'Basketball player',
        'country': 'United States'
    },
    {
        'name': 'Vin Diesel',
        'follower_count': 62,
        'description': 'Actor',
        'country': 'United States'
    },
    {
        'name': 'Cardi B',
        'follower_count': 67,
        'description': 'Musician',
        'country': 'United States'
    },
    {
        'name': 'David Beckham',
        'follower_count': 82,
        'description': 'Footballer',
        'country': 'United Kingdom'
    },
    {
        'name': 'Billie Eilish',
        'follower_count': 61,
        'description': 'Musician',
        'country': 'United States'
    },
    {
        'name': 'Justin Timberlake',
        'follower_count': 59,
        'description': 'Musician and actor',
        'country': 'United States'
    },
    {
        'name': 'UEFA Champions League',
        'follower_count': 58,
        'description': 'Club football competition',
        'country': 'Europe'
    },
    {
        'name': 'NASA',
        'follower_count': 56,
        'description': 'Space agency',
        'country': 'United States'
    },
    {
        'name': 'Emma Watson',
        'follower_count': 56,
        'description': 'Actress',
        'country': 'United Kingdom'
    },
    {
        'name': 'Shawn Mendes',
        'follower_count': 57,
        'description': 'Musician',
        'country': 'Canada'
    },
    {
        'name': 'Virat Kohli',
        'follower_count': 55,
        'description': 'Cricketer',
        'country': 'India'
    },
    {
        'name': 'Gigi Hadid',
        'follower_count': 54,
        'description': 'Model',
        'country': 'United States'
    },
    {
        'name': 'Priyanka Chopra Jonas',
        'follower_count': 53,
        'description': 'Actress and musician',
        'country': 'India'
    },
    {
        'name': '9GAG',
        'follower_count': 52,
        'description': 'Social media platform',
        'country': 'China'
    },
    {
        'name': 'Ronaldinho',
        'follower_count': 51,
        'description': 'Footballer',
        'country': 'Brasil'
    },
    {
        'name': 'Maluma',
        'follower_count': 50,
        'description': 'Musician',
        'country': 'Colombia'
    },
    {
        'name': 'Camila Cabello',
        'follower_count': 49,
        'description': 'Musician',
        'country': 'Cuba'
    },
    {
        'name': 'NBA',
        'follower_count': 47,
        'description': 'Club Basketball Competition',
        'country': 'United States'
    }
]

In [12]:
import pandas as pd 
import random

d = pd.DataFrame(data)
d
list = d.sample(2)
print(f'a = {list.iloc[0][0]}, b = {list.iloc[1][0]}')
answer = input('a와 b 중 누구의 팔로워가 더 많을까요?')


while True :
    if answer == 'a' :
        answer = 1
    else : 
        answer = 2
    score = 0
    if answer == 1 :
        if list.iloc[0][1] > list.iloc[1][1] :
            print('정답입니다')
            score = score + 1
            break
        else : 
            print(f'당신의 점수는 {score}점 입니다')
            print(score)
            break

    if answer == 2 :
        if list.iloc[0][1] < list.iloc[1][1] :
            print('정답입니다')
            score = score + 1
            break
        else :
            print(f'당신의 점수는 {score}점 입니다')
            print(score)
            break
        

while True :
    list = pd.concat([list.iloc[[answer - 1]], d.sample(1)])
    print(f'a = {list.iloc[0][0]}, b = {list.iloc[1][0]}')
    answer = input('a와 b 중 누구의 팔로워가 더 많을까요?')
    if answer == 'a' :
        answer = 1
    else : 
        answer = 2
    
    if answer == 1 :
        if list.iloc[0][1] > list.iloc[1][1] :
            print('정답입니다')
            score = score + 1
    else : 
        print('오답입니다')
        print(f'당신의 점수는 {score}점 입니다')
        break
        
    if answer == 2 :
        if list.iloc[0][1] < list.iloc[1][1] :
            print('정답입니다')
            score = score + 1
        else :
            print('오답입니다')
            print(f'당신의 점수는 {score}점 입니다')
            break

            
# ## 이중 슬라이싱!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

a = Real Madrid CF, b = Priyanka Chopra Jonas
a와 b 중 누구의 팔로워가 더 많을까요?a
정답입니다
a = Real Madrid CF, b = Ariana Grande
a와 b 중 누구의 팔로워가 더 많을까요?b
오답입니다
당신의 점수는 1점 입니다

In [308]:
import pandas as pd 
import random


def get_random() :
    global random_list
    random_list = d.sample(2)
    return random_list

def get_SecondRandomList() :
    d.drop([random_list.index[0], random_list.index[1]], axis = 0, inplace = True)
    random_list = pd.concat([random_list.iloc[[answer - 1]], d.sample(1)])
    return random_list


print('a와 b중 고르시오')
print(f'a = {get_random().iloc[0][0]}, b = {get_random().iloc[1][0]}')
answer = input('a와 b중 고르시오')
answer = (1 if answer == 'a' else 2)
a_correct = get_random().iloc[0][1] > get_random().iloc[1][1]
b_correct = get_random().iloc[0][1] < get_random().iloc[1][1]
score = 0

if answer == 1 :
    if a_correct :
        print('정답입니다')
        score = score + 1
    else :
        print(f'오답입니다, 당신의 점수는 {score}점 입니다')
        

if answer == 2 :
    if b_correct :
        print('정답입니다')
        score = score + 1
    else :
        print(f'오답입니다, 당신의 점수는 {score}점 입니다')
        
        

while True :
    get_SecondRandomList()
    print('a와 b중 고르시오')
    print(f'a = {get_SecondRandomList().iloc[0][0]}, b = {get_SecondRandomList().iloc[1][0]}')
    answer = input('a와 b중 고르시오')
    answer = (1 if answer == 'a' else 2)
    a_correct = get_SecondRandomList().iloc[0][1] > get_SecondRandomList().iloc[1][1]
    b_correct = get_SecondRandomList().iloc[0][1] < get_SecondRandomList().iloc[1][1]
    if answer == 1 :
        if a_correct :
            print('정답입니다')
            score = score + 1
        else :
            print(f'오답입니다, 당신의 점수는 {score}점 입니다')
            break

    if answer == 2 :
        if b_correct :
            print('정답입니다')
            score = score + 1
        else :
            print(f'오답입니다, 당신의 점수는 {score}점 입니다')
            break

a와 b중 고르시오
a = Vin Diesel, b = Selena Gomez
a와 b중 고르시오a
정답입니다

UnboundLocalError: local variable 'random_list' referenced before assignment

In [259]:
a = d.sample(2)
a.index[0]
d.drop([a.index[0], a.index[1]], axis = 0, inplace = True)

,name,follower_count,description,country
0,Instagram,346,Social media platform,United States
1,Cristiano Ronaldo,215,Footballer,Portugal
2,Ariana Grande,183,Musician and actress,United States
3,Dwayne Johnson,181,Actor and professional wrestler,United States
4,Selena Gomez,174,Musician and actress,United States
5,Kylie Jenner,172,Reality TV personality and businesswoman and S...,United States
7,Lionel Messi,149,Footballer,Argentina
8,Beyoncé,145,Musician,United States
9,Neymar,138,Footballer,Brasil
10,National Geographic,135,Magazine,United States
11,Justin Bieber,133,Musician,Canada
12,Taylor Swift,131,Musician,United States
13,Kendall Jenner,127,Reality TV personality and Model,United States
14,Jennifer Lopez,119,Musician and actress,United States
15,Nicki Minaj,113,Musician,Trinidad and Tobago
16,Nike,109,Sportswear multinational,United States
17,Khloé Kardashian,108,Reality TV personality and businesswoman,United States
18,Miley Cyrus,107,Musician and actress,United States
19,Katy Perry,94,Musician,United States
20,Kourtney Kardashian,90,Reality TV personality,United States
21,Kevin Hart,89,Comedian and actor,United States
22,Ellen DeGeneres,87,Comedian,United States
23,Real Madrid CF,86,Football club,Spain
24,FC Barcelona,85,Football club,Spain
25,Rihanna,81,Musician and businesswoman,Barbados
26,Demi Lovato,80,Musician and actress,United States
27,Victoria's Secret,69,Lingerie brand,United States
28,Zendaya,68,Actress and musician,United States
29,Shakira,66,Musician,Colombia
30,Drake,65,Musician,Canada
31,Chris Brown,64,Musician,United States
32,LeBron James,63,Basketball player,United States
33,Vin Diesel,62,Actor,United States
34,Cardi B,67,Musician,United States
35,David Beckham,82,Footballer,United Kingdom
36,Billie Eilish,61,Musician,United States
37,Justin Timberlake,59,Musician and actor,United States
38,UEFA Champions League,58,Club football competition,Europe
39,NASA,56,Space agency,United States
40,Emma Watson,56,Actress,United Kingdom
41,Shawn Mendes,57,Musician,Canada
42,Virat Kohli,55,Cricketer,India
43,Gigi Hadid,54,Model,United States
45,9GAG,52,Social media platform,China
46,Ronaldinho,51,Footballer,Brasil
47,Maluma,50,Musician,Colombia
48,Camila Cabello,49,Musician,Cuba
49,NBA,47,Club Basketball Competition,United States